In [1]:
import optimization as go
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from typing import Callable

import processing as pr
import read_instances as ri

from sklearn.cluster import KMeans
import my_fuzzy_cmeans_clustering as fcm
import my_kmeans_clustering as km
import my_distances as md

In [2]:
data, problem_info = ri.obtain_instance_data('p01')

points = data[['x', 'y']]
deposit = points.iloc[[0]]
points_df = points.iloc[1:,:].copy()
normalized_points = points.apply(pr.normalize, axis=0).to_numpy()[1:]
normalized_df = points.apply(pr.normalize, axis=0).iloc[1:]
points = points.to_numpy()
warehouse = points[0]
points = np.delete(points, 0, axis=0)

In [3]:
clusters_fc, labels_fc, _ = fcm.my_fuzzy_c_means(normalized_points, c=5, metric=md.euclidean_distance)

In [4]:
clusters_fc

array([[0.18530999, 0.75302671],
       [0.31689162, 0.17658955],
       [0.43217856, 0.45637962],
       [0.83604823, 0.41964968],
       [0.74383171, 0.86350815]])

In [5]:
labels_fc

array([4, 4, 4, 1, 2, 0, 0, 0, 3, 3, 2, 2, 1, 0, 1, 3, 1, 2, 1, 4, 3, 4,
       0, 0, 0, 0, 2, 4, 3, 3, 4, 2, 3, 3, 4, 4, 1, 3, 3, 1, 1, 1, 0, 1,
       1, 2, 2, 0, 3, 3], dtype=int64)

In [6]:
clusters_k, labels_k, _ = km.my_kmeans(normalized_points, normalized_df, k=5, max_iterations=10, metric=md.euclidean_distance)

In [7]:
clusters_k

array([[0.625     , 0.42460317],
       [0.36896552, 0.48783069],
       [0.51567398, 0.53102453],
       [0.62298851, 0.60952381],
       [0.49137931, 0.42460317]])

In [8]:
labels_k

array([3, 3, 3, 1, 4, 1, 1, 3, 4, 2, 4, 0, 1, 1, 2, 3, 0, 1, 1, 3, 3, 3,
       1, 1, 1, 3, 1, 3, 3, 2, 3, 3, 2, 2, 3, 3, 2, 4, 2, 1, 1, 2, 1, 2,
       2, 0, 0, 1, 2, 3], dtype=int64)